### ISSUE TITLE
Preview error when using, in nested blocks, an Umb.PropertyEditorUi.ContentPicker on 3.0.0 with umbraco 15.1.1

### ISSUE THREAD

**Issue by isIulian** [rickbutterfield/Our.Umbraco.BlockPreview#87]
### Which Umbraco.Community.BlockPreview version are you using?

3.0.0

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

15.1.1

### Bug summary

In a umbraco project I'm using the packages blockgrid to create a block of products.
The products property is a Nested BlockList in which you can use a block to populate
the product card or one with a content picker to point to specific doc types of the tree.
On nested block the content picker is of the property **_Umb.PropertyEditorUi.ContentPicker_**
and when setted with a value the generated preview for the backoffice fails.

![Image](https://github.com/user-attachments/assets/45905c61-bdb4-4228-b4c8-725a3a52c3e7)

However, with a direct block and the same property type the problem isn't happening.

![Image](https://github.com/user-attachments/assets/84889d11-b59e-42ac-9164-d97cd729bf68)

```
System.FormatException: String "[{"type": "document"" is not a valid udi.
   at Umbraco.Cms.Core.UdiParser.ParseInternal(String s, Boolean tryParse, Boolean knownTypes, Udi& udi)
   at Umbraco.Cms.Core.UdiParser.Parse(String s)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
   at Umbraco.Cms.Core.PropertyEditors.ValueConverters.MultiNodeTreePickerValueConverter.ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, Object source, Boolean preview)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType.ConvertSourceToInter(IPublishedElement owner, Object source, Boolean preview)
   at Umbraco.Cms.Core.PublishedCache.PublishedElementPropertyBase.GetInterValue()
   at Umbraco.Cms.Core.PublishedCache.PublishedElementPropertyBase.GetValue(String culture, String segment)
   at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback publishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Extensions.PublishedElementExtensions.Value[T](IPublishedElement content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Cms.Web.Common.PublishedModels.SingleProductInternalPreviewBlock.get_PreviewContent() in umbraco-based-project\umbraco\models\SingleProductInternalPreviewBlock.generated.cs:line 66
   at AspNetCoreGeneratedDocument.Views_Partials_blockgrid_Components_productsPreviewBlock_productsPreviewBlock.ExecuteAsync() in umbraco-based-project\Views\Partials\blockgrid\Components\productsPreviewBlock\productsPreviewBlock.cshtml:line 48
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkupFromPartial(ControllerContext controllerContext, ViewDataDictionary viewData, String contentAlias, BlockType blockType)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkupFromPartial(ControllerContext controllerContext, ViewDataDictionary viewData, String contentAlias, BlockType blockType)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkup(ControllerContext controllerContext, String contentAlias, ViewDataDictionary viewData, BlockType blockType)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.RenderGridBlock(String blockData, IPublishedContent content, ControllerContext controllerContext, String blockEditorAlias, Guid documentTypeUnique, String contentKey, String settingsKey)
   at Umbraco.Community.BlockPreview.Controllers.BlockPreviewApiController.PreviewGridBlock(String blockData, Guid nodeKey, String blockEditorAlias, String contentElementAlias, String culture, Guid documentTypeUnique, String contentUdi, String settingsUdi)
```

The exception is in the `UdiParser` class of Umbraco that receives a bad formatted from the property value converter `MultiNodeTreePickerValueConverter.ConvertSourceToIntermediate`

Ps. I'm not sure is related but with contentPicker there are some older [issues/74](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/issues/74)

### Steps to reproduce

- Register a BlockList property on a document type
- Setup the BlockList property to add a block that itself has BlockList Property
- The **nested BlockList** should be configured with a block that a property of
_Umb.PropertyEditorUi.ContentPicker_. 

Blocks setup from document page:
- PageBlocks
    - Products Previews
        - Preview Card (to manually populate the card data)
        - Content Preview Card (content Picker to select node and autofill card from node fields)

### Expected result / actual result

Indifferently from the nested level of the content picker property the preview should be generated.

**Comment by rickbutterfield** [comment]
@isIulian as with #88, I'm hoping to have a fix released for this tomorrow 🤞

**Comment by rickbutterfield** [comment]
@isIulian v3.2.0 is now on NuGet, please test and report back!

**Comment by rickbutterfield** [comment]
@isIulian as reported on #88, v3.2.1 is on NuGet now with another fix for this issue

**Comment by isIulian** [comment]
Hi @rickbutterfield, sorry for the late response. I was a little busy with some tasks and wanted to test the "feature fix" without haste.
Today I updated directly to the version 3.2.3, still doesn't work with content picker in a block that is used in blockgrid (nested or not).

![Image](https://github.com/user-attachments/assets/a821327c-0592-4c89-aa03-d725c5bef1f8)
Direct block

![Image](https://github.com/user-attachments/assets/a272437b-b865-480a-a43d-006209526aec)
Nested block

The message and stacktrace of the exception is still the same.
Let me know if I can look up some configuration, logs, etc... to pinpoint the possible problem.

PS. I tried version 3.2.0, 3.2.1 and 3.2.3 of the package to ensure is not a possible regression on latest version

**Comment by rickbutterfield** [comment]
@isIulian this is very odd as I can't see the same behaviour on my test site! Please can you confirm what version number is showing up under Packages section > Installed tab?

Also, are you still running Umbraco 15.1.1 or have you upgraded to 15.2?

**Comment by isIulian** [comment]
@rickbutterfield on the project I'm using 3.0.0 at the moment.

I will upgrade it to 3.2.3 in the next days.
I tested with this version on a dedicated branch not the main one of the project for now.
As for Umbraco I'm still on 15.1.1.

I will try to make the same configuration on the test site on the repository and will let you know or share somehow if on the test site will verify the same problem to have the same base.

Thank you

**Comment by snappercrumpleddog** [comment]
@rickbutterfield Just to let you know that we are getting the same error on Umbraco version 15.2 and version 3.2.4 of the BlockPreview.

![Image](https://github.com/user-attachments/assets/f12cde6f-3ea2-43dc-8cea-cee90de44a65)

**Comment by panoramaSjors** [comment]
@rickbutterfield I am also getting this exact error. I am using Umbraco 15.3 and version 3.2.4 of BlockPreview

**Comment by rickbutterfield** [comment]
Hey @isIulian, @snappercrumpleddog and @panoramaSjors - please can you all try v3.3.0 and report back? Thanks!

**Comment by panoramaSjors** [comment]
@rickbutterfield I have tested it, and I no longer get the error. Thanks, you are awesome!

**Comment by isIulian** [comment]
Hi @rickbutterfield , I have verified and with the version 3.3.0 the error is resolved.
Thank you very much for you work and dedicated time

Ps. To let you and everyone I have that Umbraco was upgraded for other reasons to 15.2.3.
So I didn't tested the feature with my original request/issue setup.

**Comment by AleksandrRogov** [comment]
@rickbutterfield looks like this error is back again 🥲. Tested in 16.3.2 with v4.0.3 of the BlockPreview.

<img width="268" height="142" alt="Image" src="https://github.com/user-attachments/assets/4c140870-d245-4224-b6d6-5b2f25b2d850" />

```
System.FormatException: String "[{"type":"document"" is not a valid udi.
   at Umbraco.Cms.Core.UdiParser.ParseInternal(String s, Boolean tryParse, Boolean knownTypes, Udi& udi)
   at Umbraco.Cms.Core.UdiParser.Parse(String s)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
   at Umbraco.Cms.Core.PropertyEditors.ValueConverters.MultiNodeTreePickerValueConverter.ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, Object source, Boolean preview)
   at Umbraco.Cms.Core.PublishedCache.PublishedElementPropertyBase.GetValue(String culture, String segment)
   at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback publishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Extensions.PublishedElementExtensions.Value[T](IPublishedElement content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   <...REDACTED...>/ViewComponents/Navigation.cs:line 60
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_Partials_blockgrid_Components_navigationWidget.__Generated__NavigationViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_Partials_blockgrid_Components_navigationWidget.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkupFromPartial(ControllerContext controllerContext, ViewDataDictionary viewData, String contentAlias, BlockType blockType)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkupFromPartial(ControllerContext controllerContext, ViewDataDictionary viewData, String contentAlias, BlockType blockType)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkup(ControllerContext controllerContext, String contentAlias, ViewDataDictionary viewData, BlockType blockType)
   at Umbraco.Community.BlockPreview.Services.BlockPreviewService.RenderGridBlock(String blockData, IPublishedContent content, ControllerContext controllerContext, String blockEditorAlias, Guid documentTypeUnique, String contentKey, String settingsKey, Nullable`1 blockIndex)
   at Umbraco.Community.BlockPreview.Controllers.BlockPreviewApiController.PreviewGridBlock(String blockData, Guid nodeKey, String blockEditorAlias, String contentElementAlias, String culture, Guid documentTypeUnique, String contentUdi, String settingsUdi, Nullable`1 blockIndex)
```

The error happens when hitting the following line in the view component:

```cs
navigationModel ??= model?.Value<IPublishedContent>(PublishedValueFallback, "model");
```

**Comment by andreami85** [comment]
> [@rickbutterfield](https://github.com/rickbutterfield) looks like this error is back again 🥲. Tested in 16.3.2 with v4.0.3 of the BlockPreview.
> 
> <img alt="Image" width="268" height="142" src="https://private-user-images.githubusercontent.com/1893650/505275278-4c140870-d245-4224-b6d6-5b2f25b2d850.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzMjMzNTYsIm5iZiI6MTc2MzMyMzA1NiwicGF0aCI6Ii8xODkzNjUwLzUwNTI3NTI3OC00YzE0MDg3MC1kMjQ1LTQyMjQtYjZkNi01YjJmMjViMmQ4NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMTZUMTk1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE0ZjhlNTBiNWRiN2FhOTU5ZmU1NTgxNTllY2FmZWM4YzFiNDU2YzJiM2I5ZWYxZTFlMGFjMmYyNTg1YzM3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OzCRuaRtA7bf09pnqj4i3d80E8NGTURZh8PP9qzQ-s4">
> ```
> System.FormatException: String "[{"type":"document"" is not a valid udi.
>    at Umbraco.Cms.Core.UdiParser.ParseInternal(String s, Boolean tryParse, Boolean knownTypes, Udi& udi)
>    at Umbraco.Cms.Core.UdiParser.Parse(String s)
>    at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
>    at Umbraco.Cms.Core.PropertyEditors.ValueConverters.MultiNodeTreePickerValueConverter.ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, Object source, Boolean preview)
>    at Umbraco.Cms.Core.PublishedCache.PublishedElementPropertyBase.GetValue(String culture, String segment)
>    at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback publishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
>    at Umbraco.Extensions.PublishedElementExtensions.Value[T](IPublishedElement content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
>    <...REDACTED...>/ViewComponents/Navigation.cs:line 60
>    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
>    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
>    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
>    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
>    at AspNetCoreGeneratedDocument.Views_Partials_blockgrid_Components_navigationWidget.__Generated__NavigationViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
>    at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
>    at AspNetCoreGeneratedDocument.Views_Partials_blockgrid_Components_navigationWidget.ExecuteAsync()
>    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
>    at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkupFromPartial(ControllerContext controllerContext, ViewDataDictionary viewData, String contentAlias, BlockType blockType)
>    at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkupFromPartial(ControllerContext controllerContext, ViewDataDictionary viewData, String contentAlias, BlockType blockType)
>    at Umbraco.Community.BlockPreview.Services.BlockPreviewService.GetMarkup(ControllerContext controllerContext, String contentAlias, ViewDataDictionary viewData, BlockType blockType)
>    at Umbraco.Community.BlockPreview.Services.BlockPreviewService.RenderGridBlock(String blockData, IPublishedContent content, ControllerContext controllerContext, String blockEditorAlias, Guid documentTypeUnique, String contentKey, String settingsKey, Nullable`1 blockIndex)
>    at Umbraco.Community.BlockPreview.Controllers.BlockPreviewApiController.PreviewGridBlock(String blockData, Guid nodeKey, String blockEditorAlias, String contentElementAlias, String culture, Guid documentTypeUnique, String contentUdi, String settingsUdi, Nullable`1 blockIndex)
> ```
> 
> The error happens when hitting the following line in the view component:
> 
> navigationModel ??= model?.Value<IPublishedContent>(PublishedValueFallback, "model");

Hi @AleksandrRogov and everyone,

I ran into exactly the same issue while using BlockPreview:
Umbraco was throwing

`String "[{"type":"document"...]" is not a valid udi.`

The problem is not BlockPreview itself, but a bug/limitation in Umbraco’s core MultiNodeTreePicker ValueConverter.
Depending on how Umbraco serializes MNTP values, the Delivery API sometimes sends:

classic CSV UDI strings

JSON arrays of UDI strings

or JSON objects like:

{ "type": "document", "unique": "3afbc063-4433-44de-9b2c-b611e0f405e0" }


The default converter only understands the CSV format, so when BlockPreview requests a preview and Umbraco feeds MNTP values in the JSON-object format, the preview crashes.

**✔️ How I fixed it**

I wrote a custom MNTP value converter that safely handles all possible formats:

CSV UDI strings

JSON arrays

JsonElement / JsonNode

{ type, unique } objects coming from the newer Delivery API serializers

It parses every case and always converts the values to a valid list of Udi.
After registering this converter, BlockPreview works correctly even when Umbraco returns the newer JSON formats.

Here is the converter I used (full working implementation):

```
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using Umbraco.Cms.Core.DeliveryApi;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Models.DeliveryApi;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors.DeliveryApi;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Extensions;

namespace Umbraco.Cms.Core.PropertyEditors.ValueConverters;

/// <summary>
///     The multi node tree picker property editor value converter.
/// </summary>
[DefaultPropertyValueConverter(typeof(MustBeStringValueConverter))]
public class SafeMultiNodeTreePickerValueConverter : PropertyValueConverterBase, IDeliveryApiPropertyValueConverter
{
    private static readonly List<string> PropertiesToExclude = new()
    {
        Constants.Conventions.Content.InternalRedirectId.ToLower(CultureInfo.InvariantCulture),
        Constants.Conventions.Content.Redirect.ToLower(CultureInfo.InvariantCulture),
    };

    private readonly IMemberService _memberService;
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;
    private readonly IApiContentBuilder _apiContentBuilder;
    private readonly IApiMediaBuilder _apiMediaBuilder;
    private readonly IPublishedContentCache _contentCache;
    private readonly IPublishedMediaCache _mediaCache;
    private readonly IPublishedMemberCache _memberCache;

    public SafeMultiNodeTreePickerValueConverter(
        IUmbracoContextAccessor umbracoContextAccessor,
        IMemberService memberService,
        IApiContentBuilder apiContentBuilder,
        IApiMediaBuilder apiMediaBuilder,
        IPublishedContentCache contentCache,
        IPublishedMediaCache mediaCache,
        IPublishedMemberCache memberCache)
    {
        _umbracoContextAccessor = umbracoContextAccessor;
        _memberService = memberService;
        _apiContentBuilder = apiContentBuilder;
        _apiMediaBuilder = apiMediaBuilder;
        _contentCache = contentCache;
        _mediaCache = mediaCache;
        _memberCache = memberCache;
    }

    public override bool IsConverter(IPublishedPropertyType propertyType) =>
        propertyType.EditorAlias.Equals(Constants.PropertyEditors.Aliases.MultiNodeTreePicker);

    public override PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType)
        => PropertyCacheLevel.Snapshot;

    public override Type GetPropertyValueType(IPublishedPropertyType propertyType)
        => IsSingleNodePicker(propertyType)
            ? typeof(IPublishedContent)
            : typeof(IEnumerable<IPublishedContent>);

    public override object? ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, object? source, bool preview)
    {
        if (!propertyType.EditorAlias.Equals(Constants.PropertyEditors.Aliases.MultiNodeTreePicker))
            return null;

        var udis = new List<Udi>();

        // 1) Caso storico: CSV di UDI
        if (source is string s && !string.IsNullOrWhiteSpace(s))
        {
            foreach (var token in s.Split(Constants.CharArrays.Comma, StringSplitOptions.RemoveEmptyEntries))
            {
                var trimmed = token.Trim();
                if (UdiParser.TryParse(trimmed, out var u)) udis.Add(u);
            }
            return udis.ToArray();
        }

        // 2) Caso moderno: JSON (può arrivare come JsonArray/JsonElement/JsonNode)
        // 2a) JsonArray (System.Text.Json.Nodes)
        if (source is JsonArray arr)
        {
            ExtractFromJsonArray(arr, udis);
            return udis.ToArray();
        }

        // 2b) JsonElement che rappresenta un array
        if (source is JsonElement el && el.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in el.EnumerateArray())
            {
                TryAddUdiFromJsonElement(item, udis);
            }
            return udis.ToArray();
        }

        // 2c) JsonNode generico
        if (source is JsonNode node && node is JsonArray arr2)
        {
            ExtractFromJsonArray(arr2, udis);
            return udis.ToArray();
        }

        // 3) Altri casi/valori vuoti -> nessun riferimento
        return Array.Empty<Udi>();
    }

    public override object? ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel cacheLevel, object? source, bool preview)
    {
        if (source == null)
        {
            return null;
        }

        // TODO: Inject an UmbracoHelper and create a GetUmbracoHelper method based on either injected or singleton
        if (_umbracoContextAccessor.TryGetUmbracoContext(out _))
        {
            if (propertyType.EditorAlias.Equals(Constants.PropertyEditors.Aliases.MultiNodeTreePicker))
            {
                var udis = (Udi[])source;
                var isSingleNodePicker = IsSingleNodePicker(propertyType);

                if ((propertyType.Alias != null && PropertiesToExclude.InvariantContains(propertyType.Alias)) == false)
                {
                    var multiNodeTreePicker = new List<IPublishedContent>();

                    UmbracoObjectTypes objectType = UmbracoObjectTypes.Unknown;
                    foreach (Udi udi in udis)
                    {
                        if (udi is not GuidUdi guidUdi)
                        {
                            continue;
                        }

                        IPublishedContent? multiNodeTreePickerItem = null;
                        switch (udi.EntityType)
                        {
                            case Constants.UdiEntityType.Document:
                                multiNodeTreePickerItem = GetPublishedContent(
                                    udi,
                                    ref objectType,
                                    UmbracoObjectTypes.Document,
                                    id => _contentCache.GetById(preview, guidUdi.Guid));
                                break;
                            case Constants.UdiEntityType.Media:
                                multiNodeTreePickerItem = GetPublishedContent(
                                    udi,
                                    ref objectType,
                                    UmbracoObjectTypes.Media,
                                    id => _mediaCache.GetById(guidUdi.Guid));
                                break;
                            case Constants.UdiEntityType.Member:
                                multiNodeTreePickerItem = GetPublishedContent(
                                    udi,
                                    ref objectType,
                                    UmbracoObjectTypes.Member,
                                    id =>
                                    {
                                        IMember? m = _memberService.GetById(guidUdi.Guid);
                                        if (m == null)
                                        {
                                            return null;
                                        }

                                        IPublishedContent? member = _memberCache.Get(m);
                                        return member;
                                    });
                                break;
                        }

                        if (multiNodeTreePickerItem != null &&
                            multiNodeTreePickerItem.ContentType.ItemType != PublishedItemType.Element)
                        {
                            multiNodeTreePicker.Add(multiNodeTreePickerItem);
                            if (isSingleNodePicker)
                            {
                                break;
                            }
                        }
                    }

                    if (isSingleNodePicker)
                    {
                        return multiNodeTreePicker.FirstOrDefault();
                    }

                    return multiNodeTreePicker;
                }

                // return the first nodeId as this is one of the excluded properties that expects a single id
                return udis.FirstOrDefault();
            }
        }

        return source;
    }

    public PropertyCacheLevel GetDeliveryApiPropertyCacheLevel(IPublishedPropertyType propertyType) => PropertyCacheLevel.Snapshot;

    public PropertyCacheLevel GetDeliveryApiPropertyCacheLevelForExpansion(IPublishedPropertyType propertyType) => PropertyCacheLevel.Snapshot;

    public Type GetDeliveryApiPropertyValueType(IPublishedPropertyType propertyType)
        => GetEntityType(propertyType) switch
        {
            Constants.UdiEntityType.Media => typeof(IEnumerable<IApiMedia>),
            Constants.UdiEntityType.Member => typeof(string), // unsupported
            _ => typeof(IEnumerable<IApiContent>)
        };


    public object? ConvertIntermediateToDeliveryApiObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, object? inter, bool preview, bool expanding)
    {
        IEnumerable<IApiContent> DefaultValue() => Array.Empty<IApiContent>();

        if (inter is not IEnumerable<Udi> udis)
        {
            return DefaultValue();
        }

        var entityType = GetEntityType(propertyType);

        if (entityType == "content")
        {
            // TODO Why do MNTP config saves "content" and not "document"?
            entityType = Constants.UdiEntityType.Document;
        }

        GuidUdi[] entityTypeUdis = udis.Where(udi => udi.EntityType == entityType).OfType<GuidUdi>().ToArray();
        return entityType switch
        {
            Constants.UdiEntityType.Document => entityTypeUdis.Select(udi =>
            {
                IPublishedContent? content = _contentCache.GetById(preview, udi.Guid);
                return content != null
                    ? _apiContentBuilder.Build(content)
                    : null;
            }).WhereNotNull().ToArray(),
            Constants.UdiEntityType.Media => entityTypeUdis.Select(udi =>
            {
                IPublishedContent? media = _mediaCache.GetById(udi.Guid);
                return media != null
                    ? _apiMediaBuilder.Build(media)
                    : null;
            }).WhereNotNull().ToArray(),
            Constants.UdiEntityType.Member => "(unsupported)",
            _ => DefaultValue()
        };
    }

    private static bool IsSingleNodePicker(IPublishedPropertyType propertyType) =>
        propertyType.DataType.ConfigurationAs<MultiNodePickerConfiguration>()?.MaxNumber == 1;

    private static string GetEntityType(IPublishedPropertyType propertyType) =>
        propertyType.DataType.ConfigurationAs<MultiNodePickerConfiguration>()?.TreeSource?.ObjectType ?? Constants.UdiEntityType.Document;

    /// <summary>
    ///     Attempt to get an IPublishedContent instance based on ID and content type
    /// </summary>
    /// <param name="nodeId">The content node ID</param>
    /// <param name="actualType">The type of content being requested</param>
    /// <param name="expectedType">The type of content expected/supported by <paramref name="contentFetcher" /></param>
    /// <param name="contentFetcher">A function to fetch content of type <paramref name="expectedType" /></param>
    /// <returns>
    ///     The requested content, or null if either it does not exist or <paramref name="actualType" /> does not match
    ///     <paramref name="expectedType" />
    /// </returns>
    private IPublishedContent? GetPublishedContent<T>(T nodeId, ref UmbracoObjectTypes actualType, UmbracoObjectTypes expectedType, Func<T, IPublishedContent?> contentFetcher)
    {
        // is the actual type supported by the content fetcher?
        if (actualType != UmbracoObjectTypes.Unknown && actualType != expectedType)
        {
            // no, return null
            return null;
        }

        // attempt to get the content
        IPublishedContent? content = contentFetcher(nodeId);
        if (content != null)
        {
            // if we found the content, assign the expected type to the actual type so we don't have to keep looking for other types of content
            actualType = expectedType;
        }

        return content;
    }


    private void ExtractFromJsonArray(JsonArray arr, List<Udi> udis)
    {
        foreach (var n in arr)
        {
            // item come stringa UDI "umb://document/{guid}"
            if (n is JsonValue jv && jv.TryGetValue<string>(out var s) && UdiParser.TryParse(s, out var u))
            {
                udis.Add(u);
                continue;
            }

            // item come oggetto { "type": "document", "unique": "3afbc063-4433-44de-9b2c-b611e0f405e0" }
            if (n is JsonObject jo)
            {
                var type = jo["type"]?.GetValue<string>();
                var uniqueStr = jo["unique"]?.GetValue<string>();
                if (!string.IsNullOrWhiteSpace(type) && Guid.TryParse(uniqueStr, out var g))
                {
                    udis.Add(new GuidUdi(type, g));
                }
            }
        }
    }

    private void TryAddUdiFromJsonElement(JsonElement item, List<Udi> udis)
    {
        switch (item.ValueKind)
        {
            case JsonValueKind.String:
                var s = item.GetString();
                if (!string.IsNullOrWhiteSpace(s) && UdiParser.TryParse(s, out var u)) udis.Add(u);
                break;

            case JsonValueKind.Object:
                if (item.TryGetProperty("type", out var tProp) &&
                    item.TryGetProperty("unique", out var uProp))
                {
                    var type = tProp.GetString();
                    var uniqueStr = uProp.GetString();
                    if (!string.IsNullOrWhiteSpace(type) && Guid.TryParse(uniqueStr, out var g))
                        udis.Add(new GuidUdi(type, g));
                }
                break;
        }
    }
}
```
**🛠️ Registration via Composer**

The converter must replace the core one, so I registered it in a custom Composer:

```
public class SafeMntpComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        // Remove the core MNTP converter
        builder.PropertyValueConverters().Remove<MultiNodeTreePickerValueConverter>();

        // Add the custom safe MNTP converter
        builder.PropertyValueConverters().Append<SafeMultiNodeTreePickerValueConverter>();
    }
}
```

**📌 Summary**

This is not a BlockPreview issue — it’s a core Umbraco MNTP conversion issue that surfaces more easily when BlockPreview asks Umbraco to re-render content for previews.

Until the Umbraco team updates the default converter to support the JSON-object format, a custom converter like the one above fully solves the problem.

**Comment by rickbutterfield** [comment]
Hi @AleksandrRogov, @andreami85,

I have struggled to replicate this on the latest version for Umbraco 16. Please give v4.0.5 a go and report back.

**Comment by andreami85** [comment]
> Hi [@AleksandrRogov](https://github.com/AleksandrRogov), [@andreami85](https://github.com/andreami85),
> 
> I have struggled to replicate this on the latest version for Umbraco 16. Please give v4.0.5 a go and report back.

Hi @rickbutterfield,
I’ve just tested the latest version v4.0.5 with Umbraco 16.3.4 and I can confirm that the issue is now resolved.
Blocks containing a MultiNodeTreePicker render correctly and there are no more errors.

Thanks for the quick fix! 🙌

**Comment by AleksandrRogov** [comment]
@rickbutterfield hi, can confirm it's fixed. thanks!
